<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test cluster_commands_SUITE:leave_unsuccessful result</title>
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" href="../../ct_default.css" type="text/css">
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

=== <a href="cluster_commands_suite.src.html#leave_unsuccessful-1">source code for cluster_commands_SUITE:leave_unsuccessful/1</a>

<pre>
<a name="top"></a>
=== Test case started with:
cluster_commands_SUITE:leave_unsuccessful([{watchdog,<0.14281.0>},
                                           {ctl_path,
                                            "/home/travis/build/esl/MongooseIM/dev/mongooseim_node1/bin/mongooseimctl"},
                                           {{ejabberd_cwd,ejabberd2@localhost},
                                            "/home/travis/build/esl/MongooseIM/dev/mongooseim_node2"},
                                           {preset,"internal_mnesia"},
                                           {tc_logfile,
                                            "/home/travis/build/esl/MongooseIM/test/ejabberd_tests/ct_report/ct_run.test@testing-gce-21328111-fde7-447d-a6a5-fa64f44c40a5.2016-03-25_02.24.39/ejabberd_tests.tests.cluster_commands_SUITE.logs/run.2016-03-25_02.30.42/cluster_commands_suite.leave_unsuccessful.html"},
                                           {tc_group_properties,
                                            [{name,clustering}]},
                                           {tc_group_path,[]},
                                           {data_dir,
                                            "/home/travis/build/esl/MongooseIM/test/ejabberd_tests/tests/cluster_commands_SUITE_data/"},
                                           {priv_dir,
                                            "/home/travis/build/esl/MongooseIM/test/ejabberd_tests/ct_report/ct_run.test@testing-gce-21328111-fde7-447d-a6a5-fa64f44c40a5.2016-03-25_02.24.39/ejabberd_tests.tests.cluster_commands_SUITE.logs/run.2016-03-25_02.30.42/log_private/"},
                                           {escalus_users,
                                            [{alice,
                                              [{username,<<"alicE">>},
                                               {server,<<"localhost">>},
                                               {password,<<"matygrysa">>}]},
                                             {clusterguy,
                                              [{username,<<"clusterguy">>},
                                               {server,<<"localhost">>},
                                               {host,<<"localhost">>},
                                               {password,
                                                <<"distributionftw">>},
                                               {port,5232}]}]}])

=== Current directory is "/home/travis/build/esl/MongooseIM/test/ejabberd_tests/ct_report/ct_run.test@testing-gce-21328111-fde7-447d-a6a5-fa64f44c40a5.2016-03-25_02.24.39"

=== Started at 2016-03-25 02:31:13

<br />

<div class="ct_error_notify"><b>*** CT Error Notification 2016-03-25 02:31:13.542 ***</b>
distributed_helper:'-verify_result/1-fun-0-' failed on line 69
Reason: assertEqual_failed

<a href="#end">Full error description and stacktrace</a>
</div>
<a name="end"></a>


=== Ended at 2016-03-25 02:31:13
=== location [{distributed_helper,'-verify_result/1-fun-0-',69},
              {distributed_helper,'-verify_result/1-lc$^0/1-0-',69},
              {cluster_commands_SUITE,leave_unsuccessful,<a href="cluster_commands_suite.src.html#169">169</a>},
              {test_server,ts_tc,1360},
              {test_server,run_test_case_eval1,977},
              {test_server,run_test_case_eval,925}]
=== reason = {assertEqual_failed,
                     [{module,distributed_helper},
                      {line,69},
                      {expression,"lists : member ( Element , List )"},
                      {expected,true},
                      {value,false}]}
  in function  distributed_helper:'-verify_result/1-fun-0-'/3 (distributed_helper.erl, line 69)
  in call from distributed_helper:'-verify_result/1-lc$^0/1-0-'/1 (distributed_helper.erl, line 69)
  in call from cluster_commands_SUITE:leave_unsuccessful/1 (cluster_commands_SUITE.erl, line 169)
  in call from test_server:ts_tc/3 (test_server.erl, line 1360)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 977)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 925)
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>
</p>
<div class="copyright">Copyright &copy; 2016 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!date>Fri Mar 25 2016 02:31:13<!/date><br />
</div>
</center>
</body>
</html>
